### ISSUE TITLE
Static mappings don't work in 0.3.0

### ISSUE THREAD

**Issue by mgol** [shootaroo/jit-grunt#11]
After upgrading from 0.2.3 to 0.3.0, I get the following error:

```
Warning: string is not a function Use --force to continue.
```

My configuration is as follows:

``` js
require('jit-grunt')(grunt, {
    continueOn: 'grunt-continue',
    continueOff: 'grunt-continue',
    jscs: 'grunt-jscs-checker',
    ngtemplates: 'grunt-angular-templates',
    protractor: 'grunt-protractor-runner',
    useminPrepare: 'grunt-usemin',
});
```
